DROP TABLE PRODUCT_IMAGE;
DROP TABLE PRODUCT_INFO;
DROP TABLE CATEGORY;
DROP TABLE CART;
DROP TABLE NOTICE;
DROP TABLE ORDER_PRODUCT;
DROP TABLE ORDERS;
DROP TABLE HEART_PRODUCT;
DROP TABLE REVIEW_IMAGE;
DROP TABLE REVIEW;
DROP TABLE MEMBER;



DROP SEQUENCE SEQ_IMG_RNO;  -- 리뷰 이미지 테이블의 시퀀스
DROP SEQUENCE SEQ_IMG_PNO;  -- 상품 이미지 테이블의 시퀀스

DROP SEQUENCE SEQ_NNO;  -- 공지사항 테이블의 시퀀스
DROP SEQUENCE SEQ_CTNO;   -- 카테고리 테이블의 시퀀스
DROP SEQUENCE SEQ_PNO;  -- 상품 테이블의 시퀀스 
DROP SEQUENCE SEQ_CNO;  -- 장바구니 테이블의 시퀀스
DROP SEQUENCE SEQ_ONO;  -- 주문 테이블의 시퀀스 
DROP SEQUENCE SEQ_RNO;  -- 리뷰 테이블의 시퀀스 
DROP SEQUENCE SEQ_MNO;  -- 회원 테이블의 시퀀스